### ISSUE TITLE
权限问题，可能需要增加说明

### ISSUE THREAD

**Issue by TsXor** [loonghao/photoshop-python-api#166]
**Describe the bug**
```
>>> app = ps.Application('Photoshop.Application.60')
Traceback (most recent call last):
  File "E:\Python39\lib\site-packages\photoshop\api\_core.py", line 36, in __init__
    self.app = self.instance_app(self.app_id)
  File "E:\Python39\lib\site-packages\photoshop\api\_core.py", line 125, in instance_app
    return CreateObject(self._program_name, dynamic=True)
  File "E:\Python39\lib\site-packages\comtypes\client\__init__.py", line 227, in CreateObject
    clsid = comtypes.GUID.from_progid(progid)
  File "E:\Python39\lib\site-packages\comtypes\GUID.py", line 85, in from_progid
    _CLSIDFromProgID(text_type(progid), byref(inst))
  File "_ctypes/callproc.c", line 1010, in GetResult
OSError: [WinError -2147221005] 无效的类字符串

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python39\lib\site-packages\photoshop\api\_core.py", line 40, in __init__
    self.app = self.instance_app(self._get_program_id())
  File "E:\Python39\lib\site-packages\photoshop\api\_core.py", line 141, in _get_program_id
    self.app_id = self.get_program_id().split(".")[0]
  File "E:\Python39\lib\site-packages\photoshop\api\_core.py", line 131, in get_program_id
    value = winreg.EnumKey(key, index)
OSError: [WinError 259] 没有可用的数据了。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Python39\lib\site-packages\photoshop\api\application.py", line 44, in __init__
    super().__init__(ps_version=version)
  File "E:\Python39\lib\site-packages\photoshop\api\_core.py", line 42, in __init__
    raise PhotoshopPythonAPIError(
photoshop.api.errors.PhotoshopPythonAPIError: Please check if you have Photoshop installed correctly.
```

**To Reproduce**
```
>>> import photoshop.api as ps
>>> app = ps.Application()
```

**Expected behavior**
可以成功的创建一个对象

**Screenshots**
（无）

**Desktop (please complete the following information):**
 - OS: `Windows10`
 - Photoshop Version: `CS6`
 - Python Version: `3.9.1`

**Additional context**
当ps以管理员权限运行，但是python未以管理员权限运行时会出现此错误
因为ps cs6年久失修，在win10上需要打开“以管理员权限运行”的兼容性选项才能用

以及，看到readme里的“how to get Photoshop program ID”，我觉得也应该来一段python的查询方法，这是我写的：
```python
import winreg,re
def traverse_subkey(key, keypath, func, extra=0):
  len_sk = winreg.QueryInfoKey(key)[0]
  for i in range(len_sk):
    skname =  winreg.EnumKey(key, i)
    skpath = keypath+'\\'+skname
    with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE,skpath) as sk:
      func(sk, skpath, skname, extra)
def traverse_val(key, func, extra=0):
  len_val = winreg.QueryInfoKey(key)[1]
  for i in range(len_val):
    valname,val,valtype = winreg.EnumValue(key, i)
    func(valname, val, valtype, extra)
keypath = r"SOFTWARE\Classes\CLSID"
re_pattern = "Photoshop\.Application\.\d+$"
with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE,keypath) as key:
  search_result = []
  def checkval(valname, val, valtype, extra):
    if valtype == winreg.REG_SZ:
      if re.match(re_pattern,val):
        skpath = extra
        search_result.append((val, skpath, valname))
  def checksk(sk, skpath, skname, extra):
    traverse_val(sk, checkval, skpath)
  def nested(sk, skpath, skname, extra):
    traverse_subkey(sk,skpath,checksk,extra)
  traverse_subkey(key,keypath,nested)
  print(search_result)
```

**Comment by loonghao** [comment]
@TsXor 
> app = ps.Application('Photoshop.Application.60')

这里传递的version是需要在constants先定义，然后通过version拿到comtypes所能支持的`program ID`
https://github.com/loonghao/photoshop-python-api/blob/main/photoshop/api/constants.py#L2

> 当ps以管理员权限运行，但是python未以管理员权限运行时会出现此错误
因为ps cs6年久失修，在win10上需要打开“以管理员权限运行”的兼容性选项才能用

由于CS6 这种版本太老，于现在的Javascript API变动太大，不方便兼容，当前就支持下面几个版本或者未来的新版本
![image](https://user-images.githubusercontent.com/13111745/179380867-dccd6e14-8051-492a-86fb-559165be333a.png)

> 以及，看到readme里的“how to get Photoshop program ID”，我觉得也应该来一段python的查询方法，这是我写的：

感谢你的分享，这个tips只是为了方便其他人想要知道如何获取`program ID`， 而powershell的以就已经足够满足需求了
