### ISSUE TITLE
Doesn't work with Photoshop 2022 

### ISSUE THREAD

**Issue by blunderedbishop** [loonghao/photoshop-python-api#215]
I've been using this package with Photoshop 2020 with no problems. I've seen now that 2022 is marked as supported so I gave it a try, but it doesn't work.

The same scripts that worked on 2020 run indefinitely on 2022 without doing anything. When I interrupt the script, this is the error that comes up:
```
Traceback (most recent call last):
  File "env\lib\site-packages\photoshop\api\_core.py", line 36, in __init__
    self.app = self.instance_app(self.app_id)
  File "env\lib\site-packages\photoshop\api\_core.py", line 125, in instance_app     
    return CreateObject(self._program_name, dynamic=True)
  File "env\lib\site-packages\comtypes\client\__init__.py", line 227, in CreateObject
    clsid = comtypes.GUID.from_progid(progid)
  File "env\lib\site-packages\comtypes\GUID.py", line 85, in from_progid
    _CLSIDFromProgID(text_type(progid), byref(inst))
  File "_ctypes/callproc.c", line 922, in GetResult
OSError: [WinError -2147221005] Invalid class string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "env\lib\site-packages\photoshop\api\_core.py", line 135, in get_program_id
    self.instance_app(value.split(".")[0])
  File "env\lib\site-packages\photoshop\api\_core.py", line 125, in instance_app
    return CreateObject(self._program_name, dynamic=True)
  File "env\lib\site-packages\comtypes\client\__init__.py", line 238, in CreateObject
    obj = comtypes.CoCreateInstance(clsid, clsctx=clsctx, interface=interface)
  File "env\lib\site-packages\comtypes\__init__.py", line 1265, in CoCreateInstance
    _ole32.CoCreateInstance(byref(clsid), punkouter, clsctx, byref(iid), byref(p))
  File "_ctypes/callproc.c", line 922, in GetResult
OSError: [WinError -2146959355] Server execution failed

Traceback (most recent call last):
 (***my script***)
  File "env\lib\site-packages\photoshop\api\_core.py", line 66, in __getattribute__
    return super().__getattribute__(item)
  File "env\lib\site-packages\photoshop\api\_document.py", line 64, in artLayers
    return ArtLayers(self.app.artLayers)
  File "env\lib\site-packages\photoshop\api\_artlayers.py", line 12, in __init__
    super().__init__(parent=parent)
  File "env\lib\site-packages\photoshop\api\_core.py", line 40, in __init__
    self.app = self.instance_app(self._get_program_id())
  File "env\lib\site-packages\photoshop\api\_core.py", line 141, in _get_program_id
    self.app_id = self.get_program_id().split(".")[0]
  File "env\lib\site-packages\photoshop\api\_core.py", line 135, in get_program_id
    self.instance_app(value.split(".")[0])
KeyboardInterrupt
```

**Comment by loonghao** [comment]
@blunderedbishop Could you provide your code?

By default, you need to set the corresponding version number
```python
import photoshop.api as ps
app = ps.Application(version="2022")
```
