### ISSUE TITLE
module 'photoshop' has no attribute 'Application'

### ISSUE THREAD

**Issue by lidorcohen12** [loonghao/photoshop-python-api#216]
When I run the example code it prints out
```python
Traceback (most recent call last):
  File "c:\Users\lidor\Documents\אישי\CryptoC\עדכון מחירים\start.py", line 22, in <module>  
    hello_world()
  File "c:\Users\lidor\Documents\אישי\CryptoC\עדכון מחירים\start.py", line 5, in hello_world
    app = ps.Application()
          ^^^^^^^^^^^^^^
AttributeError: module 'photoshop' has no attribute 'Application'
```
![image](https://user-images.githubusercontent.com/29375106/209120670-4b439150-4113-40fc-811e-4a2e4719027a.png)

 - OS: Windows 10
 - Photoshop Version: Photoshop-2023
 - Python Version: python-3.11.2

**Comment by Wang-Walexr** [comment]
Line 1 should be "import photoshop.api as ps" 

You are missing the ".api" after photoshop
