### ISSUE TITLE
does not function for Mac OSX because no winreg

### ISSUE THREAD

**Issue by saraphinaf** [loonghao/photoshop-python-api#224]
I tried running "test_imports.py" and got the following error:

`Traceback (most recent call last):
  File "test_imports.py", line 13, in <module>
    import photoshop
  File "/Applications/anaconda3/lib/python3.7/site-packages/photoshop/__init__.py", line 2, in <module>
    from photoshop.session import Session
  File "/Applications/anaconda3/lib/python3.7/site-packages/photoshop/session.py", line 33, in <module>
    from photoshop.api import ActionDescriptor
  File "/Applications/anaconda3/lib/python3.7/site-packages/photoshop/api/__init__.py", line 4, in <module>
    from photoshop.api.action_descriptor import ActionDescriptor
  File "/Applications/anaconda3/lib/python3.7/site-packages/photoshop/api/action_descriptor.py", line 14, in <module>
    from photoshop.api._core import Photoshop
  File "/Applications/anaconda3/lib/python3.7/site-packages/photoshop/api/_core.py", line 8, in <module>
    import winreg
ModuleNotFoundError: No module named 'winreg'`

I looked it up and it says winreg is just for windows. So does this whole API not work for Mac?

**Comment by loonghao** [comment]
Yes, this api currently only supports Windows.
