### ISSUE TITLE
COM err occurs in Replacing layer with image

### ISSUE THREAD

**Issue by yyy1227** [loonghao/photoshop-python-api#225]
Hi, Professional...
Please help me, and thanks in advance.

I am developing Python module merging two images into one document in Photoshop environment.
- photoshop-python-api 0.21.0 is installed,
- Python version is python-3.11.1-amd64, 
- and my editor is pycharm-community-2022.3.1, 
- and my pc is running on widows 10 OS.
- and Adobe Photoshop Version:  Master Collection CS6 , 13.0 (13.0 20120315.r.428 2012/03/15:21:00:00) x64

Below is suurce code.
I am trying to replace newly created Layer1 with image named "mcut_fg", 
and there already exists "mcut_bg" image on background Layer0 in document when opening new session., 
But,  Exception occurs calling  "ps.app.executeAction(replace_contents, desc)" function at line 16, in mergeImageLayer  

I copied Traceback messages in RUN console and DEBUG console into hear.

Please help....! And thanks a lot...

#----- 1. Python source code -----------------------------------------
from photoshop import Session

def mergeImageLayer(image_path):
    doc = ps.active_document
    new_image_layer = doc.artLayers.add()
    new_image_layer.kind = ps.LayerKind.NormalLayer

    input_file = image_path
    replace_contents = ps.app.stringIDToTypeID("placedLayerReplaceContents")
    desc = ps.ActionDescriptor
    idnull = ps.app.charIDToTypeID("null")
    desc.putPath(idnull, input_file)
    ps.app.executeAction(replace_contents, desc)    #  Line 16 <-------- !!!!! exception occur here  !!!!!!!!!!!!!!!!

with Session(file_path="D:\PycharmProjects\photoshop\exam\image\mcut_bg.jpg" , action="open") as ps:

    mergeImageLayer("D:\PycharmProjects\photoshop\exam\image\mcut_fg.jpg")

#----- 2. Traceback  message in RUN console ------------------------------------------
Traceback (most recent call last):
  File "D:\PycharmProjects\photoshop\exam\ImageMerge.py", line 23, in <module>
    mergeImageLayer("D:\PycharmProjects\photoshop\exam\image\mcut_fg.jpg")
  File "D:\PycharmProjects\photoshop\exam\ImageMerge.py", line 16, in mergeImageLayer
    ps.app.executeAction(replace_contents, desc, 3)
  File "D:\Python\Lib\site-packages\photoshop\api\application.py", line 354, in executeAction
    return self.app.executeAction(event_id, descriptor, display_dialogs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\comtypes\client\lazybind.py", line 182, in caller
    return self._comobj._invoke(descr.memid, descr.invkind, 0, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\comtypes\automation.py", line 745, in _invoke
    self.__com_Invoke(memid, riid_null, lcid, invkind,
_ctypes.COMError: (-2147212704, None, (None, None, None, 0, None))

Process finished with exit code 1

#----- 3. Traceback  message in DEBUG console ------------------------------------------
__exception__ = {tuple: 3}(<class '_ctypes.COMError'>, COMError(-2147212704, None, (None, None, None, 0, None)), <traceback object at 0x000002433CA3E780>)
a = {int} 287
argerr = {c_ulong} c_ulong(0)
array = {tagVARIANT_Array_3: 3} <comtypes.automation.tagVARIANT_Array_3 object at 0x000002433CA43250>
dp = {tagDISPPARAMS} <comtypes.automation.tagDISPPARAMS object at 0x000002433CA43950>
i = {int} 2
invkind = {int} 1
lcid = {int} 0
memid = {int} 1349280121
self = {POINTER(Dispatch)} <POINTER(IDispatch) ptr=0x2433b9093e8 at 2433ca42750>
var =  {tagVARIANT_} VARIANT(vt=0x0, None)

**Comment by yyy1227** [comment]
I saw that the same kind of issue was listed in #142 
I am using CS6, and there are two examples that dos'nt work in CS6 environment
Thanks a lot
