### ISSUE TITLE
Crashes on Photoshop 2023

### ISSUE THREAD

**Issue by RichardLindhout** [loonghao/photoshop-python-api#230]
**Describe the bug**
When I upgrade photoshop to the latest version I got an exception,  I want to use 2023 because of better subject selection tools (which we use)
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python310\lib\concurrent\futures\process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\photoshop\src\main_child.py", line 130, in edit_image
    with Session(action="open", file_path=load_dest, auto_close=True) as s:
  File "C:\Python\Python310\lib\site-packages\photoshop\session.py", line 339, in __enter__
    self.run_action()
  File "C:\Python\Python310\lib\site-packages\photoshop\session.py", line 329, in run_action
    _action()
  File "C:\Python\Python310\lib\site-packages\photoshop\session.py", line 318, in _action_open
    self.active_document = self.app.open(self.path)
  File "C:\Python\Python310\lib\site-packages\photoshop\api\application.py", line 385, in open
    document = self.app.open(document_file_path, document_type, as_smart_object)
  File "C:\Python\Python310\lib\site-packages\comtypes\client\dynamic.py", line 121, in __getattr__
    result = self._comobj.Invoke(dispid, _invkind=flags)
  File "C:\Python\Python310\lib\site-packages\comtypes\automation.py", line 799, in Invoke
    raise COMError(hresult, text, details)
_ctypes.COMError: (-2147352567, 'Er is een uitzondering opgetreden.', ('Ongeldig argument - argument 1\n- Vereiste waarde ontbreekt', 'Adobe Photoshop', None, 0, -2147220262))
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\photoshop\src\main_child.py", line 51, in start_editing_images
    edit_outfits(INPUT_PATH_OUTFIT, OUTPUT_PATH_OUTFIT)
  File "C:\photoshop\src\main_child.py", line 91, in edit_outfits
    edit_images(original_directory, directory_path, "automatic-action")
  File "C:\photoshop\src\main_child.py", line 117, in edit_images
    timeout(TIMEOUT_PER_IMAGE_IN_SECONDS, edit_image, input_path, output_path, action_name, file)
  File "C:\photoshop\src\main_child.py", line 238, in timeout
    return submit_response.result(timeout=t)
  File "C:\Python\Python310\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
_ctypes.COMError: (-2147352567, 'Er is een uitzondering opgetreden.', ('Ongeldig argument - argument 1\n- Vereiste waarde ontbreekt', 'Adobe Photoshop', None, 0, -2147220262))
```

**To Reproduce**
```

def edit_image(input_path: str, output_path: str, action_name: str, file: str):
    load_dest = os.path.join(input_path, file)
    out_dest = os.path.join(output_path, file)

    with Session(action="open", file_path=load_dest, auto_close=True) as s:
        # execute action for nicer and brighter colors
        if do_filter():
            s.app.doAction(action_name, action_name)

        # save results
        doc = s.active_document
        options = ps.JPEGSaveOptions(quality=12)
        doc.saveAs(out_dest, options, True)
```
**Expected behavior**
Not to crash

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Photoshop Version: Photoshop-2023 
 - Python Version: Python 3.10.5

**Additional context**
It worked in Photoshop 2022

**Comment by RichardLindhout** [comment]
Oops, I still am on version photoshop-python-api==0.19.3, so i'll try to upgrade :)

**Comment by RichardLindhout** [comment]
It also crashes if I run the action manually in photoshop, so probably nothing related to this library

**Comment by RichardLindhout** [comment]
Crashes on 24.1.1, 24.1 I'm now back on 23.5.4 and it works again :)

**Comment by RichardLindhout** [comment]
Looks like starting the session has some wrong arguments and is maybe missing some things which are required in photoshop 2023

**Comment by loonghao** [comment]
Hi @RichardLindhout , 
I have deployed a new version to support Photoshop-2023,please try upgrade use the latest version. 

Cheers!

**Comment by RichardLindhout** [comment]
```
"""
Traceback (most recent call last):
  File "C:\Python\Python310\lib\site-packages\comtypes\automation.py", line 791, in Invoke
    self.__com_Invoke(dispid, riid_null, _lcid, _invkind, byref(dp),
_ctypes.COMError: (-2147352567, 'Er is een uitzondering opgetreden.', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python310\lib\concurrent\futures\process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\photoshop\src\main_child.py", line 125, in edit_image
    with Session(action="open", file_path=load_dest, auto_close=True) as s:
  File "C:\Python\Python310\lib\site-packages\photoshop\session.py", line 341, in __enter__
    self.run_action()
  File "C:\Python\Python310\lib\site-packages\photoshop\session.py", line 331, in run_action
    _action()
  File "C:\Python\Python310\lib\site-packages\photoshop\session.py", line 320, in _action_open
    self.active_document = self.app.open(self.path)
  File "C:\Python\Python310\lib\site-packages\photoshop\api\application.py", line 384, in open
    document = self.app.open(document_file_path, document_type, as_smart_object)
  File "C:\Python\Python310\lib\site-packages\comtypes\client\dynamic.py", line 121, in __getattr__
    result = self._comobj.Invoke(dispid, _invkind=flags)
  File "C:\Python\Python310\lib\site-packages\comtypes\automation.py", line 799, in Invoke
    raise COMError(hresult, text, details)
_ctypes.COMError: (-2147352567, 'Er is een uitzondering opgetreden.', ('Ongeldig argument - argument 1\n- Vereiste waarde ontbreekt', 'Adobe Photoshop', None, 0, -2147220262))
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\photoshop\src\test_editing.py", line 26, in test_edit_images
    edit_outfits(TEST_INPUT_PATH, TEST_OUTPUT_PATH)
  File "C:\photoshop\src\main_child.py", line 86, in edit_outfits
    edit_images(original_directory, directory_path, "automatic-action")
  File "C:\photoshop\src\main_child.py", line 112, in edit_images
    timeout(TIMEOUT_PER_IMAGE_IN_SECONDS, edit_image, input_path, output_path, action_name, file)
  File "C:\photoshop\src\main_child.py", line 222, in timeout
    return submit_response.result(timeout=t)
  File "C:\Python\Python310\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
_ctypes.COMError: (-2147352567, 'Er is een uitzondering opgetreden.', ('Ongeldig argument - argument 1\n- Vereiste waarde ontbreekt', 'Adobe Photoshop', None, 0, -2147220262))
```

Still the same crash it seems

**Comment by RichardLindhout** [comment]
I've also tried 24.0.0 it also crashes, so I now switched back to 23.5.4 again :)

**Comment by loonghao** [comment]
@RichardLindhout 

Do you have multiple versions of photoshop installed locally?
Maybe you can try to use `ps_version` option to force setup use `2023`
```python
from photoshop import Session

withn Session(ps_version="2023") as api:
          xxxxx
```

**Comment by RichardLindhout** [comment]
No I uninstalled them but will try it tomorrow!

**Comment by RichardLindhout** [comment]
Wouldn’t this also crash the 23 version if I had multiple? I tried like 3 versions before switching back

**Comment by loonghao** [comment]
It seems not, I also have installed multiple versions myself, if `ps_version` is not set, it will use the first application path on the registration list by default.

**Comment by RichardLindhout** [comment]
But I have removed all the other photoshop instances, but I'll try it out in the coming week!

**Comment by RichardLindhout** [comment]
It stil does not work
```
    with Session(action="open", file_path=load_dest, auto_close=True, ps_version="2023") as s:
```

**Comment by loonghao** [comment]
> It stil does not work
> 
> ```
>     with Session(action="open", file_path=load_dest, auto_close=True, ps_version="2023") as s:
> ```

Is it possible to provide a more complete code for me to test on my machine?

**Comment by RichardLindhout** [comment]
I believe the example code in the repo also does not work in 2023

**Comment by RichardLindhout** [comment]
@loonghao do you have/run photoshop 2023?

**Comment by loonghao** [comment]
> @loonghao do you have/run photoshop 2023?

Yes. my photoshop version is `24.0.0 20221013.r.59 3a3d761  x64` and os version is `win 11`

**Comment by RichardLindhout** [comment]
Ah ok, maybe it's because we're on a VPS without a GPU
