### ISSUE TITLE
一个似乎比较罕见的报错

### ISSUE THREAD

**Issue by sgajs** [loonghao/photoshop-python-api#259]
原本PhotoShopPython-api可以稳定运行（在2023版本的Photoshop里面），但正常运行一段时间后突然弹出请使用正版Photoshop的红色警告，然后后续运行都会报以下错误：
```
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\baoall\caiwu\python_project\venv\lib\site-packages\photoshop\api\_core.py", line 66, in __getattribute__
    return super().__getattribute__(item)
AttributeError: 'Application' object has no attribute 'Open'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\baoall\caiwu\python_project\venv\lib\site-packages\comtypes\automation.py", line 792, in Invoke
    self.__com_Invoke(dispid, riid_null, _lcid, _invkind, byref(dp),
_ctypes.COMError: (-2147352567, '发生意外。', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\baoall\try3.py", line 44, in <module>
    a()
  File "C:\Users\Administrator\Desktop\baoall\try3.py", line 40, in a
    psapp.Open(path)
  File "C:\Users\Administrator\Desktop\baoall\caiwu\python_project\venv\lib\site-packages\photoshop\api\_core.py", line 68, in __getattribute__
    return getattr(self.app, item)
  File "C:\Users\Administrator\Desktop\baoall\caiwu\python_project\venv\lib\site-packages\comtypes\client\dynamic.py", line 121, in __getattr__
    result = self._comobj.Invoke(dispid, _invkind=flags)
  File "C:\Users\Administrator\Desktop\baoall\caiwu\python_project\venv\lib\site-packages\comtypes\automation.py", line 800, in Invoke
    raise COMError(hresult, text, details)
_ctypes.COMError: (-2147352567, '发生意外。', ('非法参数 - 参数 1\n- 缺少必需值', 'Adobe Photoshop', None, 0, -2147220262))
aaaaaas: 1349731151 <cparam 'P' (0x0000016C82FB4988)> 0 2 <cparam 'P' (0x0000016C8324EC50)> <cparam 'P' (0x0000016C8324ED30)> <cparam 'P' (0x0000016C8326C430)> <cparam 'P' (0x0000016C830FE708)>

进程已结束,退出代码1

```
是不是非正版的原因呢？我重新安装了2022版的Photoshop，用2022版时虽然不会跳出非正版的警告，但仍然会报上面“非法参数。。。。缺少必需值”的错误。
我有尝试使用其他电脑使用同样的代码操作非正版2023/2022版的Photoshop，都能正常运行。会不会是之前出现的非正版警告改了些设置使得我的电脑每次运行都会报“非法参数。。。。缺少必需值”这个错误呢？求大佬指明道路。。。

关于运行代码，只是普通地调用PhotoshopPython-API:
```
import photoshop.api as ps
def a():
    psapp=ps.Application()
    psapp.Open(path)
    psApp = psapp.Application.ActiveDocument

if __name__ == '__main__':
    a()
```

**Comment by loonghao** [comment]
这个我这边无法复现，我们持续关注一下
