### ISSUE TITLE
TypeError: '_Dispatch' object is not callable

### ISSUE THREAD

**Issue by marcouderzo** [loonghao/photoshop-python-api#44]
Running example(s) returns errors. Windows 10, Photoshop CC 2017, Python 3.8.7.

```
>> python3 session_hello_world.py

Traceback (most recent call last):
  File "session_hello_world.py", line 9, in <module>
    doc = adobe.app.documents.add(2000, 2000)
  File "C:\Users\marco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\photoshop_python_api-0.14.0-py3.8.egg\photoshop\api\_documents.py", line 47, in add
TypeError: '_Dispatch' object is not callable
```

**Comment by loonghao** [comment]
@marcouderzo Thanks for reporting this issue. I just want to confirm your photoshop is installed through the adobe installer or other way, because photoshop python api needs to register the COM interface in the registration list to call photoshop, this error seems is the script did not find the corresponding object. You can try other examples to see if it can run normally.
