### ISSUE TITLE
Error if enter version

### ISSUE THREAD

**Issue by ClementHector** [loonghao/photoshop-python-api#50]
**Describe the bug**

An error appears if you enter the photoshop version in the api.

**To Reproduce**

If i set version number like this:
```python
import photoshop.api as ps
app = ps.Application(version="2020")
```
It gave me this error:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\photoshop\api\application.py", line 34, in __init__
    super().__init__(ps_version=version)
  File "C:\Python37\lib\site-packages\photoshop\api\_core.py", line 32, in __init__
    self.app = self.instance_app(self.app_id)
  File "C:\Python37\lib\site-packages\photoshop\api\_core.py", line 108, in instance_app
    self._program_name = self._assemble_program_name(naming_space)
  File "C:\Python37\lib\site-packages\photoshop\api\_core.py", line 153, in _assemble_program_name
    return ".".join(names)
TypeError: sequence item 2: expected str instance, int found
```
** To resolve **
Change the content of the file constant.py by:
```python
# The photoshop version to COM progid mappings.
PHOTOSHOP_VERSION_MAPPINGS = {
    "2020": "140",
    "2019": "130",
    "2018": "120",
    "2017": "110",
    "2017": "110",
    "CS4": "11"
}
```

**Desktop :**
 - OS: [e.g. Windows10]
 - Photoshop Version: [Photoshop-2020/Photoshop-CS4]
 - Python Version: [python-3.7]

**Comment by loonghao** [comment]
@all-contributors please add ClementHector for Bug reports.

**Comment by loonghao** [comment]
@ClementHector Thank you for your report, I released a new version to fix that, Cheers.

**Comment by ClementHector** [comment]
Great, thank you for your work, it has helped me a lot!
